using AbpHideTenantSwitch.EntityFrameworkCore;
using Xunit;

namespace AbpHideTenantSwitch.EntityFrameworkCore;

public class AbpHideTenantSwitchEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<AbpHideTenantSwitchEntityFrameworkCoreFixture>
{

}
